name: build

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:

jobs:
  dart:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Build example
        working-directory: example
        run: flutter build macos --debug

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Build example
        working-directory: example
        run: flutter build windows --debug
      - name: Unit tests
        run: flutter test
